version: '2'

services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /docker/minio:/data
    restart: unless-stopped
  tensorboard:
    container_name: TensorBoard
#    without `--reload_task process`, tensorboard does show the experiments that it comes across, but it never updates
    command: tensorboard --bind_all --logdir s3://tensorboard/
#    with `--reload_task process` tensorboard does not show any logs of any experiment
#    command: tensorboard --bind_all --reload_task process --reload_interval 5.0 --logdir s3://tensorboard/
    environment:
      - S3_ENDPOINT=http://host.docker.internal:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=supersecret
      - FSSPEC_S3_ENDPOINT_URL=http://host.docker.internal:9000
      - FSSPEC_S3_KEY=admin
      - FSSPEC_S3_SECRET=supersecret
    extra_hosts:
      - host.docker.internal:host-gateway
    image: s3-tensorboard
    build:
      context: .
    ports:
      - '6006:6006'
    restart: unless-stopped